### ISSUE TITLE
Метод /api/books всегда возвращает пустой массив

### ISSUE THREAD

**Issue by leonidfeskov** [sintell/library-server#1]
Привет. У меня не правильно работает метод `/api/books` (без параметров). Он всегда возвращает пустой массив. Хотя я добавил несколько книг постом. И они действительно есть в базе. Одна книга возвращается `/api/book/1` нормально. 
Можешь проверить метод `/api/books`?
Либо он действительно не работает, либо я что-то делаю не так :slightly_smiling_face:.

Дергаю метод вот так:
```
axios.defaults.baseURL = 'http://127.0.0.1:3000/api';
axios.get('/books').then(response => {
    console.log(response.data) // здесь всегда пустой массив
})
```

Проверяю получение одной книги:
```
axios.get('/book/1').then(response => {
    console.log(response.data) // Данные возвращаются правильные
})
```

Спасибо

**Comment by sintell** [comment]
Действительно была проблема в запросе. Он ожидал, что всегда будут теги, авторы и читатели. Сделал их необязательными
